# Generated by Django 5.0.1 on 2024-02-03 08:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('faculty', 'Faculty'), ('student', 'Student'), ('guest', 'Guest')], max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=100)),
                ('dob', models.DateField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attendanance_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric', models.BooleanField()),
                ('face_recognition', models.BooleanField()),
                ('barcode', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Birthday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('registation_date', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('venue', models.TextField()),
                ('accept_new_entry', models.BooleanField()),
                ('report', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('onprocess', 'On Process'), ('completed', 'Completed'), ('hold', 'Hold')], max_length=255)),
                ('attendanance_markers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_attendance_marked', to=settings.AUTH_USER_MODEL)),
                ('paticipants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_participats', to=settings.AUTH_USER_MODEL)),
                ('type_of_attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.attendanance_type')),
            ],
        ),
        migrations.CreateModel(
            name='Event_Attendanance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
                ('paticipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances_participated', to=settings.AUTH_USER_MODEL)),
                ('person_marked_attendanance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances_marked_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=255, unique=True)),
                ('year_of_joining', models.IntegerField()),
                ('faculty_status', models.BooleanField()),
                ('dept', models.CharField(choices=[('CSE', 'Computer Science And Engineering'), ('ECE', 'Electronic And Communication Engineering')], max_length=100)),
                ('school', models.CharField(choices=[], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_creator', to='api.faculty'),
        ),
        migrations.CreateModel(
            name='KH_Club_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('3D', '3d'), ('AI', 'Ai'), ('WEB_AND_APP', 'Web_And_App'), ('IOT_AND_ROBOTICS', 'Iot_And_Robotics'), ('XOR', 'Xor'), ('CYBERSECURITY', 'Cybersecurity'), ('COMPETITIVE_PROGRAMMING', 'Competitive_Programming')], max_length=100)),
                ('permission', models.CharField(choices=[('ADMIN', 'Admin'), ('CLUB_LEADER', 'ClubLeader'), ('MEMBER', 'Member')], max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KH_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('late_night', 'Late_Night'), ('1st_year', '1st_Year'), ('holiday ', 'Holiday ')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.kh_club_members')),
            ],
        ),
        migrations.CreateModel(
            name='KH_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('onprocess', 'On Process'), ('completed', 'Completed'), ('hold', 'Hold')], max_length=255)),
                ('kh_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_team', to='api.kh_club_members')),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_led', to='api.kh_club_members')),
            ],
        ),
        migrations.CreateModel(
            name='KH_Club_Members_Attendanance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('word_done', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_attendances', to='api.kh_club_members')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kh_project')),
            ],
        ),
        migrations.CreateModel(
            name='KIDS_PunchTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(max_length=100, unique=True)),
                ('branch', models.CharField(choices=[('Btech', 'btech'), ('B.Sc', 'bsc')], max_length=100)),
                ('dept', models.CharField(choices=[('CSE', 'Computer Science And Engineering'), ('ECE', 'Electronic And Communication Engineering')], max_length=100)),
                ('school', models.CharField(choices=[], max_length=100)),
                ('year_of_joining', models.DateField()),
                ('year_of_studys', models.IntegerField()),
                ('passout_year', models.DateField()),
                ('hostel', models.CharField(max_length=255)),
                ('student_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
