# Generated by Django 5.0.1 on 2024-02-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school',
            field=models.CharField(choices=[('CSE', 'SChool of Computer science and engineering')], max_length=100),
        ),
    ]
