# Generated by Django 5.0.1 on 2024-02-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='joined_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='left_date',
        ),
    ]
