# Generated by Django 5.0.1 on 2024-01-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_joining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_studys',
            field=models.DateField(),
        ),
    ]
