# Generated by Django 5.0.1 on 2024-01-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_student_year_of_joining_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
