# Generated by Django 5.0.1 on 2024-01-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='register_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
