# Generated by Django 5.0.1 on 2024-01-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_faculty_gender_remove_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='passout_year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_studys',
            field=models.IntegerField(),
        ),
    ]
