# Generated by Django 5.0.1 on 2024-01-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_name_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
