# Generated by Django 5.0.1 on 2024-01-18 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='user_name',
            new_name='user',
        ),
    ]
