# Generated by Django 5.0.1 on 2024-01-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_name_student_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='type_of_attendance',
        ),
        migrations.RemoveField(
            model_name='event',
            name='attendanance_markers',
        ),
        migrations.RemoveField(
            model_name='event',
            name='paticipants',
        ),
        migrations.RemoveField(
            model_name='event',
            name='user',
        ),
        migrations.RemoveField(
            model_name='event_attendanance',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event_attendanance',
            name='paticipant',
        ),
        migrations.RemoveField(
            model_name='event_attendanance',
            name='person_marked',
        ),
        migrations.RemoveField(
            model_name='kh_club_members',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kh_project',
            name='kh_members',
        ),
        migrations.RemoveField(
            model_name='kh_club_members_attendanance',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kh_project',
            name='project_lead',
        ),
        migrations.RemoveField(
            model_name='kh_permission',
            name='user',
        ),
        migrations.RemoveField(
            model_name='kh_club_members_attendanance',
            name='project',
        ),
        migrations.DeleteModel(
            name='Attendanance_type',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Event_Attendanance',
        ),
        migrations.DeleteModel(
            name='KH_Club_Members',
        ),
        migrations.DeleteModel(
            name='KH_Permission',
        ),
        migrations.DeleteModel(
            name='KH_Club_Members_Attendanance',
        ),
        migrations.DeleteModel(
            name='KH_Project',
        ),
    ]
