# Generated by Django 5.0.1 on 2024-01-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AddField(
            model_name='faculty',
            name='dept',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
