# Generated by Django 5.0.1 on 2024-01-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_user_name_faculty_user_faculty_dept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('faculty', 'Faculty'), ('student', 'Student'), ('guest', 'Guest')], max_length=255),
        ),
    ]
