# Generated by Django 5.0.1 on 2024-02-14 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KH_Club_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(choices=[('3D', '3d'), ('AI', 'Ai'), ('WEB_AND_APP', 'Web_And_App'), ('IOT_AND_ROBOTICS', 'Iot_And_Robotics'), ('XOR', 'Xor'), ('CYBERSECURITY', 'Cybersecurity'), ('COMPETITIVE_PROGRAMMING', 'Competitive_Programming')], max_length=100)),
                ('permission', models.CharField(choices=[('ADMIN', 'Admin'), ('CLUB_LEADER', 'ClubLeader'), ('MEMBER', 'Member')], max_length=100)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('edited_date', models.DateTimeField(auto_now=True)),
                ('left_date', models.DateField(blank=True, null=True)),
                ('regno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='club_member', to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='KH_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('onprocess', 'On Process'), ('completed', 'Completed'), ('hold', 'Hold')], max_length=255)),
                ('kh_members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_team', to='kids.kh_club_members')),
                ('project_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_led', to='kids.kh_club_members')),
            ],
        ),
        migrations.CreateModel(
            name='KH_Club_Members_Attendanance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('word_done', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_attendances', to='kids.kh_club_members')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kh_project')),
            ],
        ),
        migrations.CreateModel(
            name='KIDS_Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('late_night', 'Late_Night'), ('1st_year', '1st_Year'), ('holiday ', 'Holiday ')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='KIDS_PunchTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
