# Generated by Django 5.0.2 on 2024-02-14 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kids', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kh_project',
            name='kh_members',
        ),
        migrations.RemoveField(
            model_name='kids_permission',
            name='user',
        ),
        migrations.AddField(
            model_name='kh_project',
            name='kh_members',
            field=models.ManyToManyField(to='kids.kh_club_members'),
        ),
        migrations.AddField(
            model_name='kids_permission',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
