# Generated by Django 5.0.2 on 2024-02-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kids', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('damaged', 'Damaged'), ('available', 'Available'), ('taken', 'Taken')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date_of_return', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_return_date', models.DateField()),
                ('project_description', models.TextField()),
                ('project_title', models.CharField(max_length=255)),
                ('permission_status', models.CharField(choices=[('rejected', 'Rejected'), ('accepted', 'Accepted'), ('hold', 'Hold')], max_length=100)),
                ('product', models.ManyToManyField(to='inventory.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kids.kh_club_members')),
            ],
        ),
        migrations.CreateModel(
            name='ProductManagment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('return_condition', models.CharField(choices=[('good', 'Good'), ('damaged', 'Damaged')], default='good', max_length=100, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.productrequest')),
            ],
        ),
    ]
